In [1]:
import numpy as np
import pandas as pd
import ast

In [2]:
credits = pd.read_csv("tmdb_5000_credits.csv")
movies = pd.read_csv("tmdb_5000_movies.csv")

In [3]:
movies.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124

In [4]:
credits.head()

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [5]:
movies.merge(credits,on='title').shape

(4809, 23)

In [6]:
movies = movies.merge(credits,on='title')

In [7]:
movies.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",...,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,285,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...",...,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466,206647,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...",...,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106,49026,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]",...,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124,49529,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [8]:
# genres , movie_id , keywords , title , overview , cast , crew ...

movies = movies[['movie_id','title','overview','genres','keywords','cast','crew']]

In [9]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [10]:
movies.isnull().sum()

movie_id    0
title       0
overview    3
genres      0
keywords    0
cast        0
crew        0
dtype: int64

In [11]:
movies.dropna(inplace=True)

In [12]:
movies.isnull().sum()

movie_id    0
title       0
overview    0
genres      0
keywords    0
cast        0
crew        0
dtype: int64

In [13]:
movies.duplicated().sum()

0

In [14]:
movies.iloc[0].genres

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [15]:
def convert(obj):
    L = []
    for i in ast.literal_eval(obj):
        L.append(i['name'])
    return L

In [16]:
movies

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."
...,...,...,...,...,...,...,...
4804,9367,El Mariachi,El Mariachi just wants to play his guitar and ...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 5616, ""name"": ""united states\u2013mexi...","[{""cast_id"": 1, ""character"": ""El Mariachi"", ""c...","[{""credit_id"": ""52fe44eec3a36847f80b280b"", ""de..."
4805,72766,Newlyweds,A newlywed couple's honeymoon is upended by th...,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 10749, ""...",[],"[{""cast_id"": 1, ""character"": ""Buzzy"", ""credit_...","[{""credit_id"": ""52fe487dc3a368484e0fb013"", ""de..."
4806,231617,"Signed, Sealed, Delivered","""Signed, Sealed, Delivered"" introduces a dedic...","[{""id"": 35, ""name"": ""Comedy""}, {""id"": 18, ""nam...","[{""id"": 248, ""name"": ""date""}, {""id"": 699, ""nam...","[{""cast_id"": 8, ""character"": ""Oliver O\u2019To...","[{""credit_id"": ""52fe4df3c3a36847f8275ecf"", ""de..."
4807,126186,Shanghai Calling,When ambitious New York attorney Sam is sent t...,[],[],"[{""cast_id"": 3, ""character"": ""Sam"", ""credit_id...","[{""credit_id"": ""52fe4ad9c3a368484e16a36b"", ""de..."
4808,25975,My Date with Drew,Ever since the second grade when he first saw ...,"[{""id"": 99, ""name"": ""Documentary""}]","[{""id"": 1523, ""name"": ""obsession""}, {""id"": 224...","[{""cast_id"": 3, ""character"": ""Herself"", ""credi...","[{""credit_id"": ""58ce021b9251415a390165d9"", ""de..."

In [17]:
movies['genres'].apply(convert)

0       [Action, Adventure, Fantasy, Science Fiction]
1                        [Adventure, Fantasy, Action]
2                          [Action, Adventure, Crime]
3                    [Action, Crime, Drama, Thriller]
4                [Action, Adventure, Science Fiction]
                            ...
4804                        [Action, Crime, Thriller]
4805                                [Comedy, Romance]
4806               [Comedy, Drama, Romance, TV Movie]
4807                                               []
4808                                    [Documentary]
Name: genres, Length: 4806, dtype: object

In [18]:
 movies['genres'] = movies['genres'].apply(convert)

In [19]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [20]:
movies['keywords'].apply(convert)

0       [culture clash, future, space war, space colon...
1       [ocean, drug abuse, exotic island, east india ...
2       [spy, based on novel, secret agent, sequel, mi...
3       [dc comics, crime fighter, terrorist, secret i...
4       [based on novel, mars, medallion, space travel...
                              ...
4804    [united states–mexico barrier, legs, arms, pap...
4805                                                   []
4806    [date, love at first sight, narration, investi...
4807                                                   []
4808            [obsession, camcorder, crush, dream girl]
Name: keywords, Length: 4806, dtype: object

In [21]:
movies['keywords'] = movies['keywords'].apply(convert)

In [22]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [23]:
def convert3(obj):
    L = []
    counter = 0
    for i in ast.literal_eval(obj):
        if counter != 3:
            L.append(i['name'])
            counter+=1
        else:
            break
    return L

In [24]:
movies['cast'].apply(convert3)

0        [Sam Worthington, Zoe Saldana, Sigourney Weaver]
1           [Johnny Depp, Orlando Bloom, Keira Knightley]
2            [Daniel Craig, Christoph Waltz, Léa Seydoux]
3            [Christian Bale, Michael Caine, Gary Oldman]
4          [Taylor Kitsch, Lynn Collins, Samantha Morton]
                              ...
4804    [Carlos Gallardo, Jaime de Hoyos, Peter Marqua...
4805         [Edward Burns, Kerry Bishé, Marsha Dietlein]
4806           [Eric Mabius, Kristin Booth, Crystal Lowe]
4807            [Daniel Henney, Eliza Coupe, Bill Paxton]
4808    [Drew Barrymore, Brian Herzlinger, Corey Feldman]
Name: cast, Length: 4806, dtype: object

In [25]:
movies['cast'] = movies['cast'].apply(convert3)

In [26]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux]","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman]","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton]","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [27]:
def fetch_director(obj):
    L = []
    for i in ast.literal_eval(obj):
        if i['job'] == 'Director':
            L.append(i['name'])
            break
    return L

In [28]:
movies['crew'].apply(fetch_director)

0           [James Cameron]
1          [Gore Verbinski]
2              [Sam Mendes]
3       [Christopher Nolan]
4          [Andrew Stanton]
               ...
4804     [Robert Rodriguez]
4805         [Edward Burns]
4806          [Scott Smith]
4807          [Daniel Hsia]
4808     [Brian Herzlinger]
Name: crew, Length: 4806, dtype: object

In [29]:
movies['crew'] = movies['crew'].apply(fetch_director)

In [30]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski]
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux]",[Sam Mendes]
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman]",[Christopher Nolan]
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton]",[Andrew Stanton]

In [31]:
movies['overview'][1]

'Captain Barbossa, long believed to be dead, has come back to life and is headed to the edge of the Earth with Will Turner and Elizabeth Swann. But nothing is quite as it seems.'

In [32]:
movies['overview'].apply(lambda x:x.split())

0       [In, the, 22nd, century,, a, paraplegic, Marin...
1       [Captain, Barbossa,, long, believed, to, be, d...
2       [A, cryptic, message, from, Bond’s, past, send...
3       [Following, the, death, of, District, Attorney...
4       [John, Carter, is, a, war-weary,, former, mili...
                              ...
4804    [El, Mariachi, just, wants, to, play, his, gui...
4805    [A, newlywed, couple's, honeymoon, is, upended...
4806    ["Signed,, Sealed,, Delivered", introduces, a,...
4807    [When, ambitious, New, York, attorney, Sam, is...
4808    [Ever, since, the, second, grade, when, he, fi...
Name: overview, Length: 4806, dtype: object

In [33]:
movies['overview'] = movies['overview'].apply(lambda x:x.split())

In [34]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski]
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux]",[Sam Mendes]
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman]",[Christopher Nolan]
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton]",[Andrew Stanton]

In [35]:
movies['genres'] = movies['genres'].apply(lambda x:[i.replace(" ","") for i in x])

In [36]:
movies['keywords'] = movies['keywords'].apply(lambda x:[i.replace(" ","") for i in x])

In [37]:
movies['cast'] = movies['cast'].apply(lambda x:[i.replace(" ","") for i in x])

In [38]:
movies['crew'] = movies['crew'].apply(lambda x:[i.replace(" ","") for i in x])

In [39]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron]
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski]
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LéaSeydoux]",[SamMendes]
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan]
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton]

In [40]:
movies['tags'] = movies['overview'] + movies['genres'] + movies['keywords'] + movies['cast'] + movies['crew']

In [41]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron],"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski],"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LéaSeydoux]",[SamMendes],"[A, cryptic, message, from, Bond’s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan],"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton],"[John, Carter, is, a, war-weary,, former, mili..."

In [42]:
new_df = movies[['movie_id','title','tags']]

In [43]:
new_df

,movie_id,title,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili..."
...,...,...,...
4804,9367,El Mariachi,"[El, Mariachi, just, wants, to, play, his, gui..."
4805,72766,Newlyweds,"[A, newlywed, couple's, honeymoon, is, upended..."
4806,231617,"Signed, Sealed, Delivered","[""Signed,, Sealed,, Delivered"", introduces, a,..."
4807,126186,Shanghai Calling,"[When, ambitious, New, York, attorney, Sam, is..."
4808,25975,My Date with Drew,"[Ever, since, the, second, grade, when, he, fi..."

In [44]:
new_df['tags'] = new_df['tags'].apply(lambda x:" ".join(x))

C:\Users\asus\AppData\Local\Temp\ipykernel_11232\3089450492.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(lambda x:" ".join(x))

In [45]:
new_df

,movie_id,title,tags
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...
4,49529,John Carter,"John Carter is a war-weary, former military ca..."
...,...,...,...
4804,9367,El Mariachi,El Mariachi just wants to play his guitar and ...
4805,72766,Newlyweds,A newlywed couple's honeymoon is upended by th...
4806,231617,"Signed, Sealed, Delivered","""Signed, Sealed, Delivered"" introduces a dedic..."
4807,126186,Shanghai Calling,When ambitious New York attorney Sam is sent t...
4808,25975,My Date with Drew,Ever since the second grade when he first saw ...

In [46]:
 new_df['tags'] = new_df['tags'].apply(lambda x:x.lower())

C:\Users\asus\AppData\Local\Temp\ipykernel_11232\4280305154.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(lambda x:x.lower())

In [47]:
new_df

,movie_id,title,tags
0,19995,Avatar,"in the 22nd century, a paraplegic marine is di..."
1,285,Pirates of the Caribbean: At World's End,"captain barbossa, long believed to be dead, ha..."
2,206647,Spectre,a cryptic message from bond’s past sends him o...
3,49026,The Dark Knight Rises,following the death of district attorney harve...
4,49529,John Carter,"john carter is a war-weary, former military ca..."
...,...,...,...
4804,9367,El Mariachi,el mariachi just wants to play his guitar and ...
4805,72766,Newlyweds,a newlywed couple's honeymoon is upended by th...
4806,231617,"Signed, Sealed, Delivered","""signed, sealed, delivered"" introduces a dedic..."
4807,126186,Shanghai Calling,when ambitious new york attorney sam is sent t...
4808,25975,My Date with Drew,ever since the second grade when he first saw ...

In [48]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=5000,stop_words='english')

In [49]:
vectors = cv.fit_transform(new_df['tags']).toarray()

In [50]:
vectors

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [51]:
vectors[0]

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [53]:
cv.get_feature_names_out()

array(['000', '007', '10', ..., 'zone', 'zoo', 'zooeydeschanel'],
      dtype=object)

In [54]:
import nltk

In [55]:
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

In [56]:
def stem(text):
    y = []
    
    for i in text.split():
        y.append(ps.stem(i))
        
    return " ".join(y)

In [57]:
new_df['tags'] = new_df['tags'].apply(stem)

C:\Users\asus\AppData\Local\Temp\ipykernel_11232\3213734980.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(stem)

In [58]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=5000,stop_words='english')

In [59]:
vectors = cv.fit_transform(new_df['tags']).toarray()

In [60]:
vectors

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [62]:
cv.get_feature_names_out()

array(['000', '007', '10', ..., 'zone', 'zoo', 'zooeydeschanel'],
      dtype=object)

In [64]:
len(cv.get_feature_names_out())

5000

In [65]:
from sklearn.metrics.pairwise import cosine_similarity

In [66]:
similarity = cosine_similarity(vectors)

In [67]:
similarity[0]

array([1.        , 0.08346223, 0.0860309 , ..., 0.04499213, 0.        ,
       0.        ])

In [68]:
sorted(similarity[0],reverse=True)

[1.0000000000000002,
 0.28676966733820225,
 0.26901379342448517,
 0.2605130246476754,
 0.255608593705383,
 0.2503866978335957,
 0.24511108480187255,
 0.24455799402225925,
 0.2367785320221084,
 0.23179316248638274,
 0.23174488732966075,
 0.2278389747471728,
 0.22528177844479153,
 0.21853668936906193,
 0.21239769762143662,
 0.2108663315950723,
 0.2105263157894737,
 0.20443988269091456,
 0.20437977982832192,
 0.20395079136182276,
 0.2029530274475215,
 0.2029530274475215,
 0.20277677641345318,
 0.20246457179963143,
 0.2020475485519274,
 0.1979082783981174,
 0.19767387315371682,
 0.1976738731537168,
 0.19672236884115843,
 0.19252140716412977,
 0.19134594929397597,
 0.19088542889273336,
 0.19088542889273336,
 0.1900748713929803,
 0.18929940971212042,
 0.18731716231633883,
 0.1873171623163388,
 0.18693292157876878,
 0.1860807318911967,
 0.18394180184548975,
 0.18394180184548975,
 0.1813690625275029,
 0.18074256993863339,
 0.17996850826633903,
 0.17954621161490197,
 0.1777046633277277,
 0.177343107178349,
 0.17699808135119718,
 0.17521916101261562,
 0.17521916101261562,
 0.17521916101261562,
 0.1748149640244195,
 0.17316974359835272,
 0.17292861596651865,
 0.1711905958155815,
 0.1711905958155815,
 0.17040572913692198,
 0.16943474841747153,
 0.1675415633166782,
 0.16742770563222897,
 0.16742770563222897,
 0.16692446522239718,
 0.16563698349810535,
 0.16452254913212452,
 0.16426202236672155,
 0.16222142113076254,
 0.16122923187750418,
 0.16059101370939324,
 0.15907119074394446,
 0.15907119074394446,
 0.15789473684210528,
 0.15737789507292674,
 0.15609763526361567,
 0.15511334686589626,
 0.1540171257313038,
 0.15389675281277312,
 0.15389675281277312,
 0.152008377581442,
 0.15018785229652767,
 0.15018785229652767,
 0.15018785229652765,
 0.14843120879858804,
 0.14843120879858804,
 0.14808721943977307,
 0.14673479641335554,
 0.14659886790209342,
 0.14601068654819693,
 0.14567913668701626,
 0.14567913668701626,
 0.14509525002200235,
 0.14509525002200235,
 0.14509525002200233,
 0.14421498760030763,
 0.14421498760030763,
 0.14350946197048198,
 0.14350946197048198,
 0.1433848336691011,
 0.1433848336691011,
 0.1433848336691011,
 0.1419745572840903,
 0.1419745572840903,
 0.14159846508095775,
 0.14159846508095775,
 0.1411956236812263,
 0.1411956236812263,
 0.1411956236812263,
 0.1411956236812263,
 0.1404878717372541,
 0.13977653617040256,
 0.1391037210186643,
 0.1391037210186643,
 0.13872950617564817,
 0.13834289277321493,
 0.13834289277321493,
 0.13834289277321493,
 0.13834289277321493,
 0.13710212427677043,
 0.13710212427677043,
 0.13710212427677043,
 0.13710212427677043,
 0.13629325512727639,
 0.13530201829834768,
 0.13530201829834768,
 0.13530201829834768,
 0.13530201829834768,
 0.13530201829834768,
 0.13518451760896877,
 0.13497638119975428,
 0.13476498501489081,
 0.13369695534647594,
 0.13369695534647594,
 0.13369695534647594,
 0.13334518676566626,
 0.13334518676566626,
 0.1324532357065044,
 0.1324532357065044,
 0.1324532357065044,
 0.13157894736842107,
 0.13124359177794215,
 0.12988108336653278,
 0.12988108336653278,
 0.12988108336653278,
 0.12977713690461004,
 0.12977713690461004,
 0.12977713690461004,
 0.12892051277806202,
 0.12824729401064427,
 0.12824729401064427,
 0.12824729401064427,
 0.12824729401064427,
 0.12824729401064427,
 0.12824729401064427,
 0.12725695259515557,
 0.12725695259515557,
 0.12725695259515557,
 0.126673647984535,
 0.12565617248750865,
 0.12565617248750865,
 0.12515654358043973,
 0.12515654358043973,
 0.12515654358043973,
 0.12515654358043973,
 0.12487810821089254,
 0.12487810821089254,
 0.12487810821089254,
 0.12487810821089254,
 0.12462194771917919,
 0.12361284651454937,
 0.12262786789699316,
 0.12262786789699316,
 0.12262786789699315,
 0.12227899701112963,
 0.12227899701112963,
 0.12227899701112963,
 0.12166606584807191,
 0.12166606584807191,
 0.12166606584807191,
 0.12072654548783007,
 0.1204950466257556,
 0.1204950466257556,
 0.1204950466257556,
 0.1204950466257556,
 0.1204950466257556,
 0.11980845957463077,
 0.11959121830873498,
 0.11959121830873498,
 0.11959121830873498,
 0.11959121830873498,
 0.11846977555181847,
 0.11846977555181847,
 0.11846977555181847,
 0.11846977555181847,
 0.11846977555181847,
 0.11803342130469506,
 0.11803342130469506,
 0.11803342130469505,
 0.11803342130469505,
 0.11803342130469505,
 0.11712303424679457,
 0.11707322644771176,
 0.11707322644771176,
 0.11707322644771176,
 0.11707322644771176,
 0.11707322644771176,
 0.116543309349613,
 0.116543309349613,
 0.116543309349613,
 0.116543309349613,
 0.1163350101494222,
 0.11587244366483038,
 0.11551284429847784,
 0.11506355109724453,
 0.1147078669352809,
 0.11470786693528089,
 0.11470786693528087,
 0.11470786693528087,
 0.11412706387705432,
 0.11357771260606365,
 0.11357771260606365,
 0.11295649894498103,
 0.11295649894498103,
 0.1124803176664619,
 0.1124803176664619,
 0.1124803176664619,
 0.11243619908556624,
 0.11239029738980327,
 0.11164843913471803,
 0.11164843913471803,
 0.11164843913471803,
 0.11164843913471803,
 0.11141412945539662,
 0.11141412945539661,
 0.11141412945539661,
 0.11128297681493143,
 0.11128297681493143,
 0.11128297681493143,
 0.11128297681493143,
 0.11092107999698035,
 0.11092107999698035,
 0.11037769642208699,
 0.11020775375559676,
 0.11020775375559674,
 0.10968169942141637,
 0.10968169942141635,
 0.10968169942141635,
 0.10968169942141635,
 0.10968169942141635,
 0.10968169942141635,
 0.10968169942141635,
 0.10936965981495178,
 0.10882143751650175,
 0.10882143751650175,
 0.10882143751650175,
 0.10882143751650175,
 0.10876595882948199,
 0.10838874619051501,
 0.10838874619051501,
 0.10838874619051501,
 0.108388746190515,
 0.10814761408717502,
 0.10814761408717502,
 0.10814761408717502,
 0.1074861545850028,
 0.10743376064838502,
 0.1068366854693644,
 0.106676149412533,
 0.106676149412533,
 0.106676149412533,
 0.10650358071057624,
 0.10650358071057624,
 0.10619884881071831,
 0.10619884881071831,
 0.10619884881071831,
 0.10619884881071831,
 0.10619884881071831,
 0.10619884881071831,
 0.10559715077387793,
 0.10559715077387793,
 0.10559715077387793,
 0.10526315789473685,
 0.10526315789473685,
 0.10526315789473685,
 0.10526315789473685,
 0.10471347707292387,
 0.10390486669322622,
 0.10390486669322622,
 0.10390486669322622,
 0.10390486669322622,
 0.10390486669322622,
 0.10390486669322622,
 0.10390486669322622,
 0.103851623099316,
 0.10385162309931599,
 0.1037571695799112,
 0.1037571695799112,
 0.1037571695799112,
 0.1037571695799112,
 0.1037571695799112,
 0.1037571695799112,
 0.1037571695799112,
 0.1037571695799112,
 0.1037571695799112,
 0.10301070542879115,
 0.10259783520851541,
 0.10259783520851541,
 0.10259783520851541,
 0.10259783520851541,
 0.10259783520851541,
 0.10259783520851541,
 0.10259783520851541,
 0.10218988991416095,
 0.10147651372376076,
 0.10147651372376076,
 0.10147651372376076,
 0.10138838820672659,
 0.101338918387628,
 0.101338918387628,
 0.10133891838762799,
 0.10060545457319173,
 0.10060545457319173,
 0.10060545457319173,
 0.10012523486435178,
 0.10012523486435178,
 0.10012523486435178,
 0.10012523486435178,
 0.10012523486435178,
 0.10012523486435178,
 0.09933992677987831,
 0.09933992677987831,
 0.09933992677987831,
 0.09933992677987831,
 0.09933992677987831,
 0.09933992677987831,
 0.09933992677987831,
 0.09933992677987831,
 0.09933992677987831,
 0.09933992677987831,
 0.09933992677987831,
 0.09933992677987831,
 0.09909250441117726,
 0.09909250441117726,
 0.0989541391990587,
 0.0989541391990587,
 0.0989541391990587,
 0.0989541391990587,
 0.0989541391990587,
 0.0989541391990587,
 0.09836118442057921,
 0.0978231976089037,
 0.0978231976089037,
 0.0978231976089037,
 0.0978231976089037,
 0.0978231976089037,
 0.0978231976089037,
 0.0978231976089037,
 0.0978231976089037,
 0.09733285267845754,
 0.09733285267845754,
 0.09733285267845754,
 0.09733285267845754,
 0.09733285267845754,
 0.09733285267845754,
 0.09733285267845754,
 0.09733285267845754,
 0.09733285267845754,
 0.09733285267845754,
 0.09733285267845754,
 0.0967301666813349,
 0.0967301666813349,
 0.09567297464698798,
 0.09567297464698798,
 0.09567297464698798,
 0.09567297464698798,
 0.09558988911273408,
 0.09544271444636668,
 0.09544271444636668,
 0.09544271444636668,
 0.09544271444636668,
 0.09544271444636668,
 0.09493290614465533,
 0.09464970485606021,
 0.09464970485606021,
 0.09365858115816941,
 0.09365858115816941,
 0.09365858115816941,
 0.09365858115816941,
 0.09365858115816941,
 0.09365858115816941,
 0.09365858115816941,
 0.09365858115816941,
 0.09365858115816941,
 0.09365858115816941,
 0.09365858115816941,
 0.09365858115816941,
 0.09365858115816941,
 0.09365858115816941,
 0.09365858115816941,
 0.09365858115816941,
 0.09365858115816941,
 0.09365858115816941,
 0.09365858115816941,
 0.09365858115816939,
 0.09269795493186431,
 0.09269795493186431,
 0.09269795493186431,
 0.09269795493186431,
 0.09269795493186431,
 0.09269795493186431,
 0.09269795493186431,
 0.09269795493186431,
 0.09269795493186431,
 0.09243423333081695,
 0.09197090092274487,
 0.09197090092274487,
 0.09197090092274487,
 0.09197090092274487,
 0.09197090092274487,
 0.09197090092274487,
 0.09197090092274487,
 0.09183979479633063,
 0.09183979479633063,
 0.09125667909262308,
 0.09125667909262308,
 0.09086217008485092,
 0.09086217008485092,
 0.09086217008485092,
 0.09086217008485092,
 0.09086217008485092,
 0.09086217008485092,
 0.09037128496931669,
 0.09037128496931669,
 0.09037128496931669,
 0.09037128496931669,
 0.09037128496931669,
 0.09037128496931669,
 0.09037128496931669,
 0.09037128496931669,
 0.09037128496931669,
 0.08998425413316952,
 0.08998425413316952,
 0.08998425413316952,
 0.08998425413316952,
 0.08998425413316952,
 0.08998425413316952,
 0.08998425413316952,
 0.08998425413316952,
 0.08998425413316952,
 0.08977310580745099,
 0.0891313035643173,
 0.08903057122447033,
 0.08885233166386385,
 0.08885233166386385,
 0.08885233166386385,
 0.08885233166386385,
 0.08885233166386385,
 0.08885233166386385,
 0.08830215713766959,
 0.08830215713766959,
 0.08830215713766959,
 0.08830215713766959,
 0.08830215713766959,
 0.08830215713766959,
 0.08830215713766959,
 0.08830215713766959,
 0.08797691788472335,
 0.08749572785196143,
 0.08749572785196143,
 0.08746392856766495,
 0.08740748201220976,
 0.08740748201220976,
 0.08740748201220976,
 0.08740748201220976,
 0.08740748201220976,
 0.08740748201220976,
 0.08740748201220976,
 0.08740748201220976,
 0.08740748201220976,
 0.08740748201220976,
 0.08671099695241201,
 0.08671099695241201,
 0.08671099695241201,
 0.08671099695241201,
 0.08671099695241201,
 0.08671099695241201,
 0.08671099695241201,
 0.08671099695241201,
 0.08603090020146065,
 0.08603090020146065,
 0.08603090020146065,
 0.08603090020146065,
 0.08603090020146065,
 0.08603090020146065,
 0.08603090020146065,
 0.08594700851870801,
 0.08594700851870801,
 0.08594700851870801,
 0.08520286456846099,
 0.08520286456846099,
 0.08471737420873576,
 0.08471737420873576,
 0.08471737420873576,
 0.08471737420873576,
 0.08471737420873576,
 0.08471737420873576,
 0.08471737420873576,
 0.08447772061910234,
 0.08447772061910234,
 0.08447772061910234,
 0.08447772061910234,
 0.08447772061910234,
 0.0837707816583391,
 0.0837707816583391,
 0.0837707816583391,
 0.0837707816583391,
 0.0837707816583391,
 0.0837707816583391,
 0.0837707816583391,
 0.0837707816583391,
 0.08346223261119858,
 0.08346223261119858,
 0.08346223261119858,
 0.08346223261119858,
 0.08346223261119858,
 0.08346223261119858,
 0.08346223261119858,
 0.08321783316232578,
 0.0830812984794528,
 0.0830812984794528,
 0.0830812984794528,
 0.08240856434303293,
 0.08240856434303293,
 0.08226127456606226,
 0.08226127456606226,
 0.08226127456606226,
 0.08226127456606226,
 0.08226127456606226,
 0.08226127456606226,
 0.08226127456606226,
 0.08226127456606226,
 0.08226127456606226,
 0.08226127456606226,
 0.08226127456606226,
 0.08226127456606226,
 0.08175191193132876,
 0.08175191193132876,
 0.08111071056538127,
 0.08111071056538127,
 0.08111071056538127,
 0.08111071056538127,
 0.08111071056538127,
 0.08111071056538127,
 0.08111071056538127,
 0.08111071056538127,
 0.08111071056538127,
 0.08111071056538127,
 0.08111071056538127,
 0.08111071056538127,
 0.08111071056538127,
 0.08111071056538127,
 0.08111071056538127,
 0.08111071056538127,
 0.08111071056538127,
 0.08111071056538127,
 0.08111071056538127,
 0.08111071056538127,
 0.08111071056538127,
 0.08111071056538127,
 0.08111071056538127,
 0.08111071056538127,
 0.08048436365855338,
 0.08000711205939975,
 0.08000711205939975,
 0.08000711205939975,
 0.08000711205939975,
 0.08000711205939975,
 0.08000711205939975,
 0.08000711205939975,
 0.08000711205939975,
 0.08000711205939975,
 0.07992075789278003,
 0.07987230638308718,
 0.07987230638308718,
 0.07987230638308718,
 0.07987230638308718,
 0.07987230638308718,
 0.0792740035289418,
 0.07894736842105264,
 0.07894736842105264,
 0.07894736842105264,
 0.07894736842105264,
 0.07894736842105264,
 0.07894736842105264,
 0.07894736842105264,
 0.07894736842105264,
 0.07894736842105264,
 0.07878168645790681,
 0.07868894753646337,
 0.07868894753646337,
 0.07868894753646337,
 0.07868894753646337,
 0.07868894753646337,
 0.07868894753646337,
 0.07868894753646337,
 0.07868894753646337,
 0.07868894753646337,
 0.07843304784240032,
 0.0781166566864507,
 0.0781166566864507,
 0.07792865001991967,
 0.07792865001991967,
 0.07792865001991967,
 0.07792865001991967,
 0.07792865001991967,
 0.07792865001991967,
 0.07792865001991967,
 0.07792865001991967,
 0.07792865001991967,
 0.07792865001991967,
 0.07755667343294813,
 0.07755667343294813,
 0.0770085628656519,
 0.07694837640638656,
 0.07694837640638656,
 0.07694837640638656,
 0.07694837640638656,
 0.07694837640638656,
 0.07694837640638656,
 0.07694837640638656,
 0.07694837640638656,
 0.07694837640638656,
 0.07694837640638656,
 0.07694837640638656,
 0.07647191129018727,
 0.07647191129018727,
 0.07647191129018727,
 0.07647191129018727,
 0.07647191129018727,
 0.07647191129018727,
 0.07647191129018727,
 0.07647191129018727,
 0.07647191129018727,
 0.07647191129018727,
 0.076004188790721,
 0.076004188790721,
 0.076004188790721,
 0.076004188790721,
 0.076004188790721,
 0.076004188790721,
 0.076004188790721,
 0.076004188790721,
 0.076004188790721,
 0.076004188790721,
 0.07594632491572426,
 0.07543142864047142,
 0.07530940414109724,
 0.07509392614826384,
 0.07509392614826384,
 0.07509392614826384,
 0.07509392614826384,
 0.07509392614826384,
 0.07509392614826384,
 0.07509392614826384,
 0.07509392614826384,
 0.07509392614826384,
 0.07509392614826384,
 0.07509392614826384,
 0.07509392614826384,
 0.07492686492653551,
 0.07443229275647868,
 0.07443229275647868,
 0.07443229275647868,
 0.07443229275647868,
 0.07443229275647868,
 0.07443229275647868,
 0.07443229275647868,
 0.07443229275647868,
 0.07443229275647868,
 0.07443229275647868,
 0.07443229275647868,
 0.07443229275647868,
 0.07443229275647868,
 0.07443229275647868,
 0.07443229275647868,
 0.07421560439929402,
 0.07421560439929402,
 0.07421560439929402,
 0.07421560439929402,
 0.07421560439929402,
 0.07394738666465357,
 0.07394738666465357,
 0.07394738666465357,
 0.0734718358370645,
 0.0734718358370645,
 0.07336739820667779,
 0.07336739820667779,
 0.07336739820667779,
 0.07336739820667779,
 0.07336739820667779,
 0.07336739820667779,
 0.07336739820667777,
 0.07336739820667777,
 0.07336739820667777,
 0.07254762501100118,
 0.07254762501100118,
 0.07254762501100118,
 0.07254762501100118,
 0.07254762501100118,
 0.07254762501100118,
 0.07254762501100118,
 0.07254762501100118,
 0.07254762501100118,
 0.07254762501100116,
 0.07254762501100116,
 0.07254762501100116,
 0.07254762501100116,
 0.07254762501100116,
 0.07254762501100116,
 0.07254762501100116,
 0.07254762501100116,
 0.07254762501100116,
 0.07254762501100116,
 0.07254762501100116,
 0.07254762501100116,
 0.07254762501100116,
 0.07254762501100116,
 0.07254762501100116,
 0.07254762501100116,
 0.07254762501100116,
 0.07254762501100116,
 0.07254762501100116,
 0.07209840939145001,
 0.07209840939145001,
 0.07175473098524099,
 0.07175473098524099,
 0.07175473098524099,
 0.07175473098524099,
 0.07175473098524099,
 0.07175473098524099,
 0.07175473098524099,
 0.07175473098524099,
 0.07175473098524099,
 0.07175473098524099,
 0.07175473098524099,
 0.07175473098524099,
 0.07175473098524099,
 0.07098727864204515,
 0.07098727864204515,
 0.07098727864204515,
 0.07098727864204515,
 0.07098727864204515,
 0.07098727864204515,
 0.07098727864204515,
 0.07098727864204515,
 0.07098727864204515,
 0.07098727864204515,
 0.07098727864204515,
 0.07098727864204515,
 0.07079923254047887,
 0.07079923254047887,
 0.07079923254047887,
 0.07079923254047887,
 0.07079923254047887,
 0.07079923254047887,
 0.07079923254047887,
 0.07038153430777869,
 0.07038153430777869,
 0.07024393586862707,
 0.07024393586862707,
 0.07024393586862707,
 0.06952346619889824,
 0.06952346619889824,
 0.06952346619889824,
 0.06952346619889824,
 0.06952346619889824,
 0.06952346619889824,
 0.06952346619889824,
 0.06952346619889824,
 0.06952346619889824,
 0.06952346619889824,
 0.06917144638660747,
 0.06917144638660747,
 0.06917144638660747,
 0.06917144638660747,
 0.06917144638660747,
 0.06882472016116853,
 0.06882472016116853,
 0.06882472016116853,
 0.06882472016116853,
 0.06882472016116853,
 0.06882472016116853,
 0.06882472016116853,
 0.06814662756363819,
 0.06814662756363819,
 0.06814662756363819,
 0.06814662756363819,
 0.06814662756363819,
 0.06814662756363819,
 0.06814662756363819,
 0.06814662756363819,
 0.06814662756363819,
 0.06814662756363819,
 0.06814662756363819,
 0.06765100914917384,
 0.06765100914917384,
 0.06765100914917384,
 0.06765100914917384,
 0.06765100914917384,
 0.06765100914917384,
 0.06765100914917384,
 0.06765100914917384,
 0.06765100914917384,
 0.06765100914917384,
 0.06765100914917384,
 0.06765100914917384,
 0.06765100914917384,
 0.06765100914917384,
 0.06765100914917384,
 0.06765100914917384,
 0.06765100914917384,
 0.06748819059987714,
 0.06748819059987714,
 0.06748819059987714,
 0.06748819059987714,
 0.06748819059987714,
 0.06748819059987714,
 0.0672863110252489,
 0.06684847767323797,
 0.06684847767323797,
 0.06684847767323797,
 0.06684847767323797,
 0.06657426652986062,
 0.0662266178532522,
 0.0662266178532522,
 0.0662266178532522,
 0.0662266178532522,
 0.0662266178532522,
 0.0662266178532522,
 0.0662266178532522,
 0.0662266178532522,
 0.0662266178532522,
 0.0662266178532522,
 0.0662266178532522,
 0.0662266178532522,
 0.0662266178532522,
 0.0662266178532522,
 0.0662266178532522,
 0.0662266178532522,
 0.06622661785325219,
 0.06622661785325219,
 0.06622661785325219,
 0.06622661785325219,
 0.06622661785325219,
 0.06622661785325219,
 0.06622661785325219,
 0.06622661785325219,
 0.06622661785325219,
 0.06622661785325219,
 0.06578947368421054,
 0.06562179588897107,
 0.06562179588897107,
 0.06562179588897107,
 0.06562179588897107,
 0.06562179588897107,
 0.06562179588897107,
 0.06562179588897107,
 0.06554735253444621,
 0.06521546507260247,
 0.065033247714309,
 0.065033247714309,
 0.065033247714309,
 0.065033247714309,
 0.065033247714309,
 0.06488856845230502,
 0.06488856845230502,
 0.06488856845230502,
 0.06488856845230502,
 0.06488856845230502,
 0.06488856845230502,
 0.06488856845230502,
 0.06488856845230502,
 0.06488856845230502,
 0.06488856845230502,
 0.06488856845230502,
 0.06488856845230502,
 0.06488856845230502,
 0.06488856845230502,
 0.06488856845230502,
 0.06488856845230502,
 0.06488856845230502,
 0.06488856845230502,
 0.06488856845230502,
 0.06488856845230502,
 0.06488856845230502,
 0.06446025638903101,
 0.06446025638903101,
 0.06446025638903101,
 0.06446025638903101,
 0.06446025638903101,
 0.06424925662032356,
 0.06390214842634574,
 0.06390214842634574,
 0.06390214842634574,
 0.06390214842634574,
 0.06390214842634574,
 0.06390214842634574,
 0.06362847629757779,
 0.06362847629757779,
 0.06362847629757779,
 0.06362847629757779,
 0.06362847629757779,
 0.06362847629757779,
 0.06362847629757779,
 0.06362847629757779,
 0.06362847629757779,
 0.06362847629757779,
 0.06362847629757779,

In [69]:
sorted(list(enumerate(similarity[0])),reverse=True,key=lambda x:x[1])[1:6]

[(1214, 0.28676966733820225),
 (2405, 0.26901379342448517),
 (3728, 0.2605130246476754),
 (507, 0.255608593705383),
 (539, 0.2503866978335957)]

In [70]:
def recommend(movie):
    movie_index = new_df[new_df['title'] == movie].index[0]
    distances = similarity[movie_index]
    movies_list = sorted(list(enumerate(distances)),reverse=True,key=lambda x:x[1])[1:6]
    
    for i in movies_list:
        print(new_df.iloc[i[0]].title)

In [71]:
recommend('Independence Day')

Independence Daysaster
Meet Dave
Aliens vs Predator: Requiem
Escape from Planet Earth
The Day the Earth Stood Still

In [80]:
recommend('The Day the Earth Stood Still')

Meet Dave
Impostor
Independence Day
Escape from Planet Earth
Alien³